# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ausdigital
baseurl: "" # the subpath of your site, e.g. /blog

markdown: kramdown
kramwdown:
  parse_block_html: true

gems: [jekyll-toc]

defaults:
  -
    scope:
      path: "specs"
      type: "pages"
    values:
      layout: "specs"
      toc: true